### ISSUE TITLE
accordion toggle stopped working

### ISSUE THREAD

**Issue by pgoldtho** [visulate/visulate-ora2pg#63]
Accordion toggle in 1.1.4 release fails with

runtime-core.esm-bundler.js:226 TypeError: Cannot read properties of undefined (reading 'toggle')
    at Proxy.toggleAccordion (Ora2PgConfig.vue:174:20)
    at onClick (Ora2PgConfig.vue:31:19)
    at o (runtime-core.esm-bundler.js:155:22)
    at l (runtime-core.esm-bundler.js:164:21)
    at HTMLHeadingElement.s (runtime-dom.esm-bundler.js:366:13)

**Comment by pgoldtho** [comment]
Possibly related:

runtime-core.esm-bundler.js?d2dd:38 [Vue warn]: Invalid prop: type check failed for prop "config". Expected Object, got Boolean with value false. 
  at <Ora2PgConfig ref="configComponent" project="default" config=false  ... > 
  at <AppContainer>
